- name: install filebeat
  yum:
    name: https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-7.9.1-x86_64.rpm

- name: put configuration
  copy:
    src: filebeat.yml
    dest: /etc/filebeat/filebeat.yml
    mode: 0644

- name: enable filebeat
  systemd:
    name: filebeat
    enabled: yes
    state: restarted
