- name: set hostname
  hostname:
    name: "{{ inventory_hostname_short }}"

- name: install tools
  yum:
    update_cache: yes
    pkg:
      - dstat
      - fish
      - graphviz
      - nano
      - unzip
