- name: set hostname
  hostname:
    name: "{{ inventory_hostname_short }}"

- name: install tools
  apt:
    update_cache: yes
    pkg:
      - dstat
      - fish
      - graphviz
      - nano
      - unzip
      - percona-toolkit

- name: create ssh dir for root
  file:
    path: /root/.ssh
    state: directory
    mode: 0700

- name: put id_rsa for root
  copy:
    src: ../hq/tun/id_rsa
    dest: /root/.ssh/id_rsa
    mode: 0600

- name: create ssh dir for isucon
  become_user: isucon
  file:
    path: /home/isucon/.ssh
    state: directory
    mode: 0700
  failed_when: false

- name: put id_rsa for isucon
  become_user: isucon
  copy:
    src: ../hq/tun/id_rsa
    dest: /home/isucon/.ssh/id_rsa
    mode: 0600
  failed_when: false

- name: put /etc/sysctl.d/isucon.conf
  copy:
    src: isucon.conf
    dest: /etc/sysctl.d/isucon.conf
    mode: 0644
  register: sysctl

- name: sysctl -p /etc/sysctl.d/isucon.conf
  command: sysctl -p /etc/sysctl.d/isucon.conf
  when: sysctl.changed

- name: create service.d
  file:
    state: directory
    path: /etc/systemd/system/{{ item }}.service.d
  loop:
    - nginx
    - mysql
    - mariadb

- name: override systemd services
  copy:
    src: override.conf
    dest: /etc/systemd/system/{{ item }}.service.d/override.conf
    mode: 0644
  loop:
    - nginx
    - mysql
    - mariadb

- name: systemd daemon-reload
  systemd:
    daemon_reload: true

- name: create /var/log/nginx
  file:
    state: directory
    path: /var/log/nginx/hit/parade/hoge
    mode: 0777

- name: touch /var/log/nginx/access.log
  file:
    state: touch
    path: /var/log/nginx/access.log
    mode: 0666
