- hosts: hq
  become: yes
  tasks:
    - name: stop containers
      command: docker-compose down
      args:
        chdir: /opt/isucon10/hq

- hosts: srv
  become: yes
  tasks:
    - name: stop services
      systemd:
        name: "{{ item }}"
        enabled: no
        state: stopped
      loop:
        - filebeat
        - netdata
